# Generated by Django 2.1.2 on 2018-10-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table=None,
        ),
    ]
