# Generated by Django 2.1.3 on 2018-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
