# Generated by Django 2.1.3 on 2018-11-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_orderinfo_oaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(max_length=150),
        ),
    ]
